name: chef19
on:
  workflow_dispatch:

jobs:
  chef19:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/thheinen/chef19
          cacheFrom: ghcr.io/thheinen/chef19
          push: always
        env:
          CHEF_LICENSE: ${{ secrets.CHEF_LICENSE }}
